# Proyecto
sonar.projectKey=tourcapachica
sonar.projectName=tourcapachica
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.test.ts

# Pruebas
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Cobertura de Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8

# Conexión a SonarQube
sonar.host.url=http://localhost:9000/
sonar.login=squ_c473d42c189b9dbfb7cc86769fa6f286c4d247ff
